-- OverwriteThisOnNextCompile=True

DROP TABLE IF EXISTS REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME;

CREATE TABLE REPLACE_ME_DB_NAME.REPLACE_ME_TABLE_NAME (
    "health_sys_id" VARCHAR(12),
    "health_sys_name" VARCHAR(56),
    "health_sys_city" VARCHAR(21),
    "health_sys_state" VARCHAR(3),
    "in_onekey" VARCHAR(2),
    "in_aha" VARCHAR(2),
    "onekey_id" VARCHAR(9),
    "aha_sysid" VARCHAR(5),
    "total_mds" VARCHAR(6),
    "prim_care_mds" VARCHAR(6),
    "total_nps" VARCHAR(5),
    "total_pas" VARCHAR(5),
    "grp_cnt" VARCHAR(5),
    "grp_cnt_restricted" VARCHAR(5),
    "hosp_cnt" VARCHAR(4),
    "acutehosp_cnt" VARCHAR(4),
    "nh_cnt" VARCHAR(4),
    "nh_cnt_restricted" VARCHAR(4),
    "hhco_cnt" VARCHAR(3),
    "hhco_cnt_restricted" VARCHAR(3),
    "sys_multistate" VARCHAR(2),
    "sys_beds" VARCHAR(6),
    "sys_dsch" VARCHAR(8),
    "sys_res" VARCHAR(8),
    "deg_children" VARCHAR(2),
    "sys_incl_majteachhosp" VARCHAR(2),
    "sys_incl_vmajteachhosp" VARCHAR(2),
    "sys_teachint" VARCHAR(2),
    "sys_incl_highdpphosp" VARCHAR(2),
    "sys_highucburden" VARCHAR(2),
    "sys_incl_highuchosp" VARCHAR(2),
    "sys_anyins_product" VARCHAR(2),
    "sys_mcare_adv" VARCHAR(2),
    "sys_mcaid_mngcare" VARCHAR(2),
    "sys_healthins_mktplc" VARCHAR(2),
    "sys_ownership" VARCHAR(2),
    "hos_net_revenue" VARCHAR(12),
    "hos_total_revenue" VARCHAR(13)
);