ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
ADD COLUMN new_NPI BIGINT;

UPDATE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
SET new_NPI = NPI::BIGINT;

ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
DROP COLUMN NPI;

ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
RENAME COLUMN new_NPI TO NPI;



