ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
ADD COLUMN new_npi BIGINT;

UPDATE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
SET new_NPI = npi::BIGINT;

ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
DROP COLUMN npi;

ALTER TABLE REPLACE_ME_DATABASE_NAME.REPLACE_ME_TABLE_NAME
RENAME COLUMN new_npi TO npi;



